# Generated by Django 4.0.2 on 2022-03-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
