# Generated by Django 4.0.2 on 2022-03-19 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_service_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='fk',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='garage.garage'),
            preserve_default=False,
        ),
    ]
