# Generated by Django 4.0.2 on 2022-03-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_service_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='garagename',
            field=models.CharField(default=111, max_length=30),
            preserve_default=False,
        ),
    ]
