# Generated by Django 4.0.2 on 2022-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_alter_service_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='mapp',
            field=models.TextField(default=111, max_length=500),
            preserve_default=False,
        ),
    ]
