# Generated by Django 4.0.2 on 2022-03-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_service_mapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='mapp',
        ),
    ]
